apiVersion: v1
kind: Pod
metadata:
  name: prodigi-pod-ff-3
  labels:
    app: prodigi-importer-pod
  namespace: services
spec:
  containers:
  - name: migrator-pod
    image: yellowmessenger.azurecr.io/agents-service:master-v1163
    env:
      - name: "SERVICE_NAME"
        value: "salesforce-test"
    command:
      - "node"
      - "app.js"
    resources:
      limits:
        memory: "1Gi"
        cpu: "500m"
      requests:
        cpu: 500m
        memory: 1Gi
    volumeMounts:
        - mountPath: /config
          name: config-file
          readOnly: true
  volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config.yml
            path: config.yml
          name: project-config
        name: config-file
  imagePullSecrets:
  - name: regcreds
